module.exports = {
	INVALID_DATA: field => `DATA NOT SEND OR INVALID: '${field}'`,
	INVALID_ENTITY_ID: id => `INVALID ID: '${id}'`,
	TASK_NOT_EXISTS: 'TASK NOT EXISTS',
	INVALID_CREDENTIALS: 'INVALID CREDENTIALS',
	USER_NOT_AUTHORIZED: 'USER NOT AUTHORIZED',
	NO_TOKEN_PROVIDED: 'NO TOKEN PROVIDED',
	INVALID_TOKEN: 'INVALID TOKEN'
};